// Auto-generated by pg2ts
// https://github.com/indiekitai/pg2ts
// Do not edit manually!

export interface AdminLogs {
  id: number;
  admin_id: number;
  action: string;
  target_type?: string;
  target_id?: number;
  /** PostgreSQL type: jsonb */
  details?: unknown;
  ip?: string;
  user_agent?: string;
  created_at: number;
}

export interface AdminSessions {
  id: number;
  admin_id: number;
  device_type?: string;
  browser?: string;
  os?: string;
  ip_address?: string;
  location?: string;
  user_agent?: string;
  is_current?: boolean;
  created_at: number;
  last_active_at: number;
}

export interface Admins {
  id: number;
  email: string;
  password_hash: string;
  name: string;
  avatar?: string;
  role: string;
  permissions?: string[];
  twofa_enabled?: boolean;
  twofa_secret?: string;
  login_attempts?: number;
  locked_until?: number;
  last_login_at?: number;
  last_login_ip?: string;
  status?: string;
  created_at: number;
  updated_at: number;
  phone?: string;
  bio?: string;
  /** PostgreSQL type: jsonb */
  notification_preferences?: unknown;
}

export interface Articles {
  id: number;
  author_id?: number;
  title: string;
  summary?: string;
  content: string;
  cover_url?: string;
  category: string;
  tags?: string[];
  video_url?: string;
  video_duration?: number;
  is_vip_only?: boolean;
  is_ai_generated?: boolean;
  is_pinned?: boolean;
  sort_order?: number;
  recommend_level?: number;
  /** PostgreSQL type: jsonb */
  metadata?: unknown;
  status?: string;
  published_at?: number;
  views_count?: number;
  likes_count?: number;
  shares_count?: number;
  created_at: number;
  updated_at: number;
  content_type: string;
  reject_reason?: string;
  comments_count?: number;
  favorites_count?: number;
  dislikes_count?: number;
}

export interface Banners {
  id: number;
  title: string;
  image_url: string;
  link_type: string;
  link_value: string;
  position?: string;
  start_at?: number;
  end_at?: number;
  status?: string;
  sort_order?: number;
  created_at: number;
  updated_at?: number;
}

export interface ChatMessages {
  id: number;
  room_id: number;
  sender_type?: string;
  user_id?: number;
  admin_id?: number;
  type: string;
  content: string;
  reply_to?: number;
  is_pinned?: boolean;
  pinned_at?: number;
  pinned_by?: number;
  pinned_by_type?: string;
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  is_deleted?: boolean;
  created_at: number;
}

export interface ChatRoomJoinRequests {
  id: number;
  room_id: number;
  user_id: number;
  message?: string;
  status?: string;
  handled_by?: number;
  handled_by_type?: string;
  handled_at?: number;
  reject_reason?: string;
  created_at: number;
}

export interface ChatRoomMembers {
  id: number;
  room_id: number;
  user_id: number;
  role?: string;
  last_read_at?: number;
  last_read_msg_id?: number;
  is_muted?: boolean;
  muted_until?: number;
  muted_by?: number;
  muted_by_type?: string;
  mute_reason?: string;
  joined_at: number;
}

export interface ChatRooms {
  id: number;
  owner_type?: string;
  owner_id?: number;
  admin_owner_id?: number;
  name?: string;
  avatar?: string;
  description?: string;
  type: string;
  is_vip_only?: boolean;
  require_approval?: boolean;
  allow_image?: boolean;
  is_muted?: boolean;
  join_announcement?: string;
  members_count?: number;
  messages_count?: number;
  status?: string;
  created_at: number;
  updated_at: number;
  last_message_content?: string;
  last_message_at?: number;
  last_message_user_id?: number;
}

export interface Comments {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  parent_id?: number;
  reply_to_user?: number;
  content: string;
  likes_count?: number;
  status?: string;
  created_at: number;
}

export interface DirectMessageParticipants {
  id: number;
  room_id: number;
  user1_id: number;
  user2_id: number;
  created_at: number;
}

export interface Favorites {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  created_at: number;
}

export interface FlashNews {
  id: number;
  author_id?: number;
  content: string;
  importance?: string;
  sentiment?: string;
  related_assets?: string[];
  source?: string;
  status?: string;
  published_at?: number;
  created_at: number;
  title?: string;
  category?: string;
  /** PostgreSQL type: jsonb */
  market_impact?: unknown;
  source_url?: string;
  tags?: string[];
  is_pinned?: boolean;
  is_hot?: boolean;
  is_push_enabled?: boolean;
  reject_reason?: string;
  views_count?: number;
  updated_at: number;
}

export interface ForumInviteCodes {
  id: number;
  forum_id: number;
  code: string;
  created_by?: number;
  created_by_type?: string;
  max_uses?: number;
  used_count?: number;
  expires_at?: number;
  status?: string;
  created_at: number;
}

export interface ForumMembers {
  id: number;
  forum_id: number;
  user_id: number;
  role?: string;
  invite_code_id?: number;
  joined_at: number;
}

export interface Forums {
  id: number;
  name: string;
  description?: string;
  icon?: string;
  cover_url?: string;
  color?: string;
  access_level?: string;
  post_permission?: string;
  /** PostgreSQL type: jsonb */
  rules?: unknown;
  announcement?: string;
  announcement_at?: number;
  members_count?: number;
  posts_count?: number;
  today_posts?: number;
  status?: string;
  sort_order?: number;
  created_at: number;
  updated_at: number;
}

export interface KolApplications {
  id: number;
  user_id: number;
  reason: string;
  /** PostgreSQL type: jsonb */
  social_links?: unknown;
  proof_urls?: string[];
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  applied_level?: string;
  approved_level?: string;
  created_at: number;
  updated_at?: number;
}

export interface Likes {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  created_at: number;
}

export interface Notifications {
  id: number;
  user_id: number;
  type: string;
  title: string;
  content?: string;
  action_type?: string;
  action_id?: number;
  is_read?: boolean;
  created_at: number;
}

export interface PlatformSettings {
  id: number;
  key: string;
  /** PostgreSQL type: jsonb */
  value: unknown;
  description?: string;
  category?: string;
  updated_by?: number;
  updated_at: number;
}

export interface PointProducts {
  id: number;
  name: string;
  description?: string;
  image_url?: string;
  category?: string;
  points_price: number;
  original_price?: number;
  stock?: number;
  sold_count?: number;
  limit_per_user?: number;
  vip_only?: boolean;
  status?: string;
  sort_order?: number;
  start_at?: number;
  end_at?: number;
  created_at: number;
  updated_at: number;
}

export interface PointRecords {
  id: number;
  user_id: number;
  type: string;
  points: number;
  balance: number;
  ref_type?: string;
  ref_id?: number;
  description?: string;
  created_at: number;
}

export interface PointRedeemOrders {
  id: number;
  user_id: number;
  product_id: number;
  order_no: string;
  points_cost: number;
  quantity?: number;
  /** PostgreSQL type: jsonb */
  shipping_info?: unknown;
  redeem_code?: string;
  redeem_url?: string;
  status?: string;
  shipped_at?: number;
  completed_at?: number;
  admin_note?: string;
  created_at: number;
}

export interface PollOptions {
  id: number;
  poll_id: number;
  content: string;
  sort_order?: number;
  votes_count?: number;
  created_at: number;
}

export interface PollVotes {
  id: number;
  poll_id: number;
  option_id: number;
  user_id: number;
  created_at: number;
}

export interface Polls {
  id: number;
  creator_id: number;
  target_type?: string;
  target_id?: number;
  title: string;
  description?: string;
  is_multiple?: boolean;
  is_anonymous?: boolean;
  max_choices?: number;
  end_at?: number;
  votes_count?: number;
  voters_count?: number;
  status?: string;
  created_at: number;
}

export interface PostTopics {
  id: number;
  post_id: number;
  topic_id: number;
  created_at: number;
}

export interface Posts {
  id: number;
  forum_id: number;
  user_id?: number;
  admin_id?: number;
  author_type?: string;
  category?: string;
  title: string;
  content: string;
  images?: string[];
  tags?: string[];
  is_pinned?: boolean;
  is_featured?: boolean;
  is_locked?: boolean;
  views_count?: number;
  likes_count?: number;
  comments_count?: number;
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  created_at: number;
  updated_at: number;
  /** PostgreSQL type: jsonb */
  widgets?: unknown;
  dislikes_count?: number;
}

export interface Reactions {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  reaction_type: string;
  created_at: number;
}

export interface Reports {
  id: number;
  reporter_id: number;
  target_type: string;
  target_id: number;
  reason: string;
  description?: string;
  evidence_urls?: string[];
  status?: string;
  handled_by?: number;
  handled_at?: number;
  action_taken?: string;
  action_note?: string;
  created_at: number;
}

export interface SchemaMigrations {
  version: string;
  applied_at: number;
}

export interface SignalTracks {
  id: number;
  user_id: number;
  signal_id: number;
  tracked_at: number;
}

export interface Signals {
  id: number;
  user_id: number;
  title: string;
  asset?: string;
  direction?: string;
  leverage?: number;
  entry_price?: number;
  target_prices?: number[];
  stop_loss?: number;
  current_price?: number;
  risk_reward?: string;
  position_size?: string;
  analysis?: string;
  chart_url?: string;
  status?: string;
  result?: string;
  pnl_percent?: number;
  closed_at?: number;
  is_vip_only?: boolean;
  vip_level?: string;
  is_pinned?: boolean;
  pinned_at?: number;
  recommend_level?: number;
  trackers_count?: number;
  likes_count?: number;
  comments_count?: number;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  review_notes?: string;
  created_at: number;
  updated_at: number;
  signal_type?: string;
  prediction_platform?: string;
  event_category?: string;
  prediction_event?: string;
  current_probability?: number;
  probability_change_24h?: number;
  trading_volume?: string;
  prediction_direction?: string;
  indicator_type?: string;
  indicator_value?: string;
  signal_direction?: string;
  signal_strength?: string;
  expires_at?: number;
  visibility?: string;
  is_push_enabled?: boolean;
  allow_comments?: boolean;
  timeframe?: string;
}

export interface TopicFollows {
  id: number;
  user_id: number;
  topic_id: number;
  created_at: number;
}

export interface Topics {
  id: number;
  name: string;
  description?: string;
  icon?: string;
  posts_count?: number;
  followers_count?: number;
  participants_count?: number;
  views_count?: number;
  is_hot?: boolean;
  is_recommended?: boolean;
  sort_order?: number;
  status?: string;
  created_at: number;
  updated_at: number;
}

export interface UserBlocks {
  id: number;
  blocker_id: number;
  blocked_id: number;
  reason?: string;
  created_at: number;
}

export interface UserExchangeBindings {
  id: number;
  user_id: number;
  exchange: string;
  exchange_uid?: string;
  api_key?: string;
  api_secret?: string;
  passphrase?: string;
  permissions?: string[];
  status?: string;
  is_primary?: boolean;
  last_sync_at?: number;
  sync_error?: string;
  created_at: number;
  updated_at: number;
}

export interface UserFollows {
  id: number;
  follower_id: number;
  following_id: number;
  created_at: number;
}

export interface UserInvites {
  id: number;
  inviter_id: number;
  invitee_id: number;
  invite_code?: string;
  inviter_reward?: number;
  invitee_reward?: number;
  reward_status?: string;
  registered_at?: number;
  rewarded_at?: number;
  created_at: number;
}

export interface UserWatchlists {
  id: number;
  user_id: number;
  symbol: string;
  exchange?: string;
  sort_order?: number;
  created_at: number;
}

export interface Users {
  id: number;
  username: string;
  email?: string;
  phone?: string;
  avatar?: string;
  bio?: string;
  wallet_address?: string;
  wallet_type?: string;
  vip_level?: string;
  vip_expire_at?: number;
  is_kol?: boolean;
  kol_level?: string;
  kol_verified_at?: number;
  followers_count?: number;
  following_count?: number;
  signals_count?: number;
  win_rate?: number;
  likes_count?: number;
  posts_count?: number;
  points?: number;
  total_pnl?: number;
  total_trades?: number;
  exchange_bound?: boolean;
  status?: string;
  ban_reason?: string;
  banned_at?: number;
  wallet_verified_at?: number;
  /** PostgreSQL type: jsonb */
  preferences?: unknown;
  admin_note?: string;
  invite_code?: string;
  last_login_at?: number;
  last_login_ip?: string;
  register_ip?: string;
  register_source?: string;
  created_at: number;
  updated_at: number;
  kol_suspended_at?: number;
  kol_suspend_reason?: string;
  kol_status?: string;
  /** PostgreSQL type: jsonb */
  stats?: unknown;
  email_verified?: boolean;
  email_verified_at?: number;
  profile_completed?: boolean;
  profile_completed_at?: number;
  apple_id?: string;
  auth_provider?: string;
}

export interface VipOrders {
  id: number;
  user_id: number;
  plan_id?: number;
  order_no: string;
  vip_level: string;
  amount: number;
  original_amount?: number;
  payment_method: string;
  payment_address?: string;
  tx_hash?: string;
  status?: string;
  paid_at?: number;
  expire_at?: number;
  vip_start_at?: number;
  vip_end_at?: number;
  created_at: number;
  product_id?: string;
  transaction_id?: string;
  receipt_data?: string;
  purchase_token?: string;
  platform?: string;
  verified_at?: number;
  /** PostgreSQL type: jsonb */
  verify_result?: unknown;
}

export interface VipPlans {
  id: number;
  name: string;
  level: string;
  description?: string;
  price: number;
  original_price?: number;
  duration_days?: number;
  /** PostgreSQL type: jsonb */
  features?: unknown;
  is_active?: boolean;
  sort_order?: number;
  created_at: number;
  updated_at: number;
}

// Helper types for insert/update operations

export type AdminLogsInsert = {
  id: number;
  admin_id: number;
  action: string;
  created_at: number;
  target_type?: string;
  target_id?: number;
  details?: unknown;
  ip?: string;
  user_agent?: string;
};

export type AdminSessionsInsert = {
  id: number;
  admin_id: number;
  created_at: number;
  last_active_at: number;
  device_type?: string;
  browser?: string;
  os?: string;
  ip_address?: string;
  location?: string;
  user_agent?: string;
  is_current?: boolean;
};

export type AdminsInsert = {
  id: number;
  email: string;
  password_hash: string;
  name: string;
  created_at: number;
  updated_at: number;
  avatar?: string;
  role?: string;
  permissions?: string[];
  twofa_enabled?: boolean;
  twofa_secret?: string;
  login_attempts?: number;
  locked_until?: number;
  last_login_at?: number;
  last_login_ip?: string;
  status?: string;
  phone?: string;
  bio?: string;
  notification_preferences?: unknown;
};

export type ArticlesInsert = {
  id: number;
  title: string;
  content: string;
  category: string;
  created_at: number;
  updated_at: number;
  author_id?: number;
  summary?: string;
  cover_url?: string;
  tags?: string[];
  video_url?: string;
  video_duration?: number;
  is_vip_only?: boolean;
  is_ai_generated?: boolean;
  is_pinned?: boolean;
  sort_order?: number;
  recommend_level?: number;
  metadata?: unknown;
  status?: string;
  published_at?: number;
  views_count?: number;
  likes_count?: number;
  shares_count?: number;
  content_type?: string;
  reject_reason?: string;
  comments_count?: number;
  favorites_count?: number;
  dislikes_count?: number;
};

export type BannersInsert = {
  id: number;
  title: string;
  image_url: string;
  link_type: string;
  link_value: string;
  created_at: number;
  position?: string;
  start_at?: number;
  end_at?: number;
  status?: string;
  sort_order?: number;
  updated_at?: number;
};

export type ChatMessagesInsert = {
  id: number;
  room_id: number;
  type: string;
  content: string;
  created_at: number;
  sender_type?: string;
  user_id?: number;
  admin_id?: number;
  reply_to?: number;
  is_pinned?: boolean;
  pinned_at?: number;
  pinned_by?: number;
  pinned_by_type?: string;
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  is_deleted?: boolean;
};

export type ChatRoomJoinRequestsInsert = {
  id: number;
  room_id: number;
  user_id: number;
  created_at: number;
  message?: string;
  status?: string;
  handled_by?: number;
  handled_by_type?: string;
  handled_at?: number;
  reject_reason?: string;
};

export type ChatRoomMembersInsert = {
  id: number;
  room_id: number;
  user_id: number;
  joined_at: number;
  role?: string;
  last_read_at?: number;
  last_read_msg_id?: number;
  is_muted?: boolean;
  muted_until?: number;
  muted_by?: number;
  muted_by_type?: string;
  mute_reason?: string;
};

export type ChatRoomsInsert = {
  id: number;
  type: string;
  created_at: number;
  updated_at: number;
  owner_type?: string;
  owner_id?: number;
  admin_owner_id?: number;
  name?: string;
  avatar?: string;
  description?: string;
  is_vip_only?: boolean;
  require_approval?: boolean;
  allow_image?: boolean;
  is_muted?: boolean;
  join_announcement?: string;
  members_count?: number;
  messages_count?: number;
  status?: string;
  last_message_content?: string;
  last_message_at?: number;
  last_message_user_id?: number;
};

export type CommentsInsert = {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  content: string;
  created_at: number;
  parent_id?: number;
  reply_to_user?: number;
  likes_count?: number;
  status?: string;
};

export type DirectMessageParticipantsInsert = {
  id: number;
  room_id: number;
  user1_id: number;
  user2_id: number;
  created_at: number;
};

export type FavoritesInsert = {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  created_at: number;
};

export type FlashNewsInsert = {
  id: number;
  content: string;
  created_at: number;
  updated_at: number;
  author_id?: number;
  importance?: string;
  sentiment?: string;
  related_assets?: string[];
  source?: string;
  status?: string;
  published_at?: number;
  title?: string;
  category?: string;
  market_impact?: unknown;
  source_url?: string;
  tags?: string[];
  is_pinned?: boolean;
  is_hot?: boolean;
  is_push_enabled?: boolean;
  reject_reason?: string;
  views_count?: number;
};

export type ForumInviteCodesInsert = {
  id: number;
  forum_id: number;
  code: string;
  created_at: number;
  created_by?: number;
  created_by_type?: string;
  max_uses?: number;
  used_count?: number;
  expires_at?: number;
  status?: string;
};

export type ForumMembersInsert = {
  id: number;
  forum_id: number;
  user_id: number;
  joined_at: number;
  role?: string;
  invite_code_id?: number;
};

export type ForumsInsert = {
  id: number;
  name: string;
  created_at: number;
  updated_at: number;
  description?: string;
  icon?: string;
  cover_url?: string;
  color?: string;
  access_level?: string;
  post_permission?: string;
  rules?: unknown;
  announcement?: string;
  announcement_at?: number;
  members_count?: number;
  posts_count?: number;
  today_posts?: number;
  status?: string;
  sort_order?: number;
};

export type KolApplicationsInsert = {
  id: number;
  user_id: number;
  reason: string;
  created_at: number;
  social_links?: unknown;
  proof_urls?: string[];
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  applied_level?: string;
  approved_level?: string;
  updated_at?: number;
};

export type LikesInsert = {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  created_at: number;
};

export type NotificationsInsert = {
  id: number;
  user_id: number;
  type: string;
  title: string;
  created_at: number;
  content?: string;
  action_type?: string;
  action_id?: number;
  is_read?: boolean;
};

export type PlatformSettingsInsert = {
  id: number;
  key: string;
  value: unknown;
  updated_at: number;
  description?: string;
  category?: string;
  updated_by?: number;
};

export type PointProductsInsert = {
  id: number;
  name: string;
  points_price: number;
  created_at: number;
  updated_at: number;
  description?: string;
  image_url?: string;
  category?: string;
  original_price?: number;
  stock?: number;
  sold_count?: number;
  limit_per_user?: number;
  vip_only?: boolean;
  status?: string;
  sort_order?: number;
  start_at?: number;
  end_at?: number;
};

export type PointRecordsInsert = {
  id: number;
  user_id: number;
  type: string;
  points: number;
  balance: number;
  created_at: number;
  ref_type?: string;
  ref_id?: number;
  description?: string;
};

export type PointRedeemOrdersInsert = {
  id: number;
  user_id: number;
  product_id: number;
  order_no: string;
  points_cost: number;
  created_at: number;
  quantity?: number;
  shipping_info?: unknown;
  redeem_code?: string;
  redeem_url?: string;
  status?: string;
  shipped_at?: number;
  completed_at?: number;
  admin_note?: string;
};

export type PollOptionsInsert = {
  id: number;
  poll_id: number;
  content: string;
  created_at: number;
  sort_order?: number;
  votes_count?: number;
};

export type PollVotesInsert = {
  id: number;
  poll_id: number;
  option_id: number;
  user_id: number;
  created_at: number;
};

export type PollsInsert = {
  id: number;
  creator_id: number;
  title: string;
  created_at: number;
  target_type?: string;
  target_id?: number;
  description?: string;
  is_multiple?: boolean;
  is_anonymous?: boolean;
  max_choices?: number;
  end_at?: number;
  votes_count?: number;
  voters_count?: number;
  status?: string;
};

export type PostTopicsInsert = {
  id: number;
  post_id: number;
  topic_id: number;
  created_at: number;
};

export type PostsInsert = {
  id: number;
  forum_id: number;
  title: string;
  content: string;
  created_at: number;
  updated_at: number;
  user_id?: number;
  admin_id?: number;
  author_type?: string;
  category?: string;
  images?: string[];
  tags?: string[];
  is_pinned?: boolean;
  is_featured?: boolean;
  is_locked?: boolean;
  views_count?: number;
  likes_count?: number;
  comments_count?: number;
  status?: string;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  widgets?: unknown;
  dislikes_count?: number;
};

export type ReactionsInsert = {
  id: number;
  user_id: number;
  target_type: string;
  target_id: number;
  reaction_type: string;
  created_at: number;
};

export type ReportsInsert = {
  id: number;
  reporter_id: number;
  target_type: string;
  target_id: number;
  reason: string;
  created_at: number;
  description?: string;
  evidence_urls?: string[];
  status?: string;
  handled_by?: number;
  handled_at?: number;
  action_taken?: string;
  action_note?: string;
};

export type SchemaMigrationsInsert = {
  version: string;
  applied_at: number;
};

export type SignalTracksInsert = {
  id: number;
  user_id: number;
  signal_id: number;
  tracked_at: number;
};

export type SignalsInsert = {
  id: number;
  user_id: number;
  title: string;
  created_at: number;
  updated_at: number;
  asset?: string;
  direction?: string;
  leverage?: number;
  entry_price?: number;
  target_prices?: number[];
  stop_loss?: number;
  current_price?: number;
  risk_reward?: string;
  position_size?: string;
  analysis?: string;
  chart_url?: string;
  status?: string;
  result?: string;
  pnl_percent?: number;
  closed_at?: number;
  is_vip_only?: boolean;
  vip_level?: string;
  is_pinned?: boolean;
  pinned_at?: number;
  recommend_level?: number;
  trackers_count?: number;
  likes_count?: number;
  comments_count?: number;
  reviewed_by?: number;
  reviewed_at?: number;
  reject_reason?: string;
  review_notes?: string;
  signal_type?: string;
  prediction_platform?: string;
  event_category?: string;
  prediction_event?: string;
  current_probability?: number;
  probability_change_24h?: number;
  trading_volume?: string;
  prediction_direction?: string;
  indicator_type?: string;
  indicator_value?: string;
  signal_direction?: string;
  signal_strength?: string;
  expires_at?: number;
  visibility?: string;
  is_push_enabled?: boolean;
  allow_comments?: boolean;
  timeframe?: string;
};

export type TopicFollowsInsert = {
  id: number;
  user_id: number;
  topic_id: number;
  created_at: number;
};

export type TopicsInsert = {
  id: number;
  name: string;
  created_at: number;
  updated_at: number;
  description?: string;
  icon?: string;
  posts_count?: number;
  followers_count?: number;
  participants_count?: number;
  views_count?: number;
  is_hot?: boolean;
  is_recommended?: boolean;
  sort_order?: number;
  status?: string;
};

export type UserBlocksInsert = {
  id: number;
  blocker_id: number;
  blocked_id: number;
  created_at: number;
  reason?: string;
};

export type UserExchangeBindingsInsert = {
  id: number;
  user_id: number;
  exchange: string;
  created_at: number;
  updated_at: number;
  exchange_uid?: string;
  api_key?: string;
  api_secret?: string;
  passphrase?: string;
  permissions?: string[];
  status?: string;
  is_primary?: boolean;
  last_sync_at?: number;
  sync_error?: string;
};

export type UserFollowsInsert = {
  id: number;
  follower_id: number;
  following_id: number;
  created_at: number;
};

export type UserInvitesInsert = {
  id: number;
  inviter_id: number;
  invitee_id: number;
  created_at: number;
  invite_code?: string;
  inviter_reward?: number;
  invitee_reward?: number;
  reward_status?: string;
  registered_at?: number;
  rewarded_at?: number;
};

export type UserWatchlistsInsert = {
  id: number;
  user_id: number;
  symbol: string;
  created_at: number;
  exchange?: string;
  sort_order?: number;
};

export type UsersInsert = {
  id: number;
  username: string;
  created_at: number;
  updated_at: number;
  email?: string;
  phone?: string;
  avatar?: string;
  bio?: string;
  wallet_address?: string;
  wallet_type?: string;
  vip_level?: string;
  vip_expire_at?: number;
  is_kol?: boolean;
  kol_level?: string;
  kol_verified_at?: number;
  followers_count?: number;
  following_count?: number;
  signals_count?: number;
  win_rate?: number;
  likes_count?: number;
  posts_count?: number;
  points?: number;
  total_pnl?: number;
  total_trades?: number;
  exchange_bound?: boolean;
  status?: string;
  ban_reason?: string;
  banned_at?: number;
  wallet_verified_at?: number;
  preferences?: unknown;
  admin_note?: string;
  invite_code?: string;
  last_login_at?: number;
  last_login_ip?: string;
  register_ip?: string;
  register_source?: string;
  kol_suspended_at?: number;
  kol_suspend_reason?: string;
  kol_status?: string;
  stats?: unknown;
  email_verified?: boolean;
  email_verified_at?: number;
  profile_completed?: boolean;
  profile_completed_at?: number;
  apple_id?: string;
  auth_provider?: string;
};

export type VipOrdersInsert = {
  id: number;
  user_id: number;
  order_no: string;
  vip_level: string;
  amount: number;
  payment_method: string;
  created_at: number;
  plan_id?: number;
  original_amount?: number;
  payment_address?: string;
  tx_hash?: string;
  status?: string;
  paid_at?: number;
  expire_at?: number;
  vip_start_at?: number;
  vip_end_at?: number;
  product_id?: string;
  transaction_id?: string;
  receipt_data?: string;
  purchase_token?: string;
  platform?: string;
  verified_at?: number;
  verify_result?: unknown;
};

export type VipPlansInsert = {
  id: number;
  name: string;
  level: string;
  price: number;
  created_at: number;
  updated_at: number;
  description?: string;
  original_price?: number;
  duration_days?: number;
  features?: unknown;
  is_active?: boolean;
  sort_order?: number;
};
